### ISSUE TITLE
canarymod not loading plug-in

### ISSUE THREAD

**Issue by nshiff** [Macuyiko/minecraft-python#2]
Received the following error while loading the latest (version d79b26a0cb2b7fbe8e9ce628617d5436dd5f8465 from 2015-02-26)

```
[03:39:59] [CanaryMod] [ERROR]: Exception while enabling plugin: CanaryConsole
net.canarymod.exceptions.PluginLoadFailedException: Failed to load plugin
        at net.canarymod.plugin.lifecycle.JavaPluginLifecycle._load(JavaPluginLifecycle.java:36) ~[canary.jar:1.8.0-1.2.0]
        at net.canarymod.plugin.lifecycle.PluginLifecycleBase.load(PluginLifecycleBase.java:73) ~[canary.jar:1.8.0-1.2.0]
        at net.canarymod.plugin.DefaultPluginManager.enablePlugin(DefaultPluginManager.java:73) ~[canary.jar:1.8.0-1.2.0]
        at net.canarymod.plugin.DefaultPluginManager.enableLatePlugins(DefaultPluginManager.java:110) [canary.jar:1.8.0-1.2.0]
        at net.canarymod.Canary.enableLatePlugins(Canary.java:296) [canary.jar:1.8.0-1.2.0]
    at net.minecraft.server.dedicated.DedicatedServer.i(DedicatedServer.java:330) [canary.jar:1.8.0-1.2.0]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:450) [canary.jar:1.8.0-1.2.0]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.ClassNotFoundException: The     class com.macuyiko.canaryconsole.MainPlugin could not be found!
        at net.canarymod.CanaryClassLoader.findCI htink lass(CanaryClassLoader.java:56) ~[canary.jar:1.8.0-1.2.0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
        at net.canarymod.plugin.lifecycle.JavaPluginLifecycle._load(JavaPluginLifecycle.java:26) ~[canary.jar:1.8.0-1.2.0]
        ... 7 more
```

I want to be careful and say, I'm not demanding a fix or anything like that. I'm just letting you know that perhaps something isn't working the way you think it is. Are you testing on Ubuntu? I am running Ubuntu 14.04 on the Amazon server. I'll confess that I haven't been trying on Windows, since it is tangential to my goal. (Theoretically I could run a Windows server on Amazon, but I am hoping that can stay as Plan B. I find Linux much easier to work with, particularly if I'm limited to the command line.)

From my perspective, the version I used in the [video](https://www.youtube.com/watch?v=O7xMgtMgMGw) was working great. Honestly I am perfectly happy running with the PlaceInCanaryMod version - I haven't combed through the code enough to recognize how the ServerPluginInterpreter is better, faster, stronger.

**Comment by Macuyiko** [comment]
I think the reason might be because you are using Java 7. This is probably also the reason why you get the compilation errors for the editor.

The instructions I sent before were executed on Ubuntu 14.04. What do you get for `java -version`? Mine gives:

```
webmaster@tengwesta:~$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

I'll look into recompiling the plugin with Java 7 if needed...

**Comment by Macuyiko** [comment]
I've just commited a new version compiled with Java 7. Can you try again with that one?

**Comment by nshiff** [comment]
Yep, you got it. Nice work, my friend. I just did 

```
sudo apt-get install default-jre
```

on Ubuntu, which apparently is still Java 7. I can just install 8 if that's easier, but initializing the server works great! I actually made a little startup script because I was getting tired of typing it in every time, ha ha. https://github.com/gamestartdev/canarymod-deploy-here
