### ISSUE TITLE
IOException Error

### ISSUE THREAD

**Issue by Magikh42** [Macuyiko/minecraft-python#23]
I got an error at loading
The Plugin still work correctly

```
[16:08:48 INFO]: IOException on socket listen: java.net.BindException: Address already in use: JVM_Bind
[16:08:48 WARN]: java.net.BindException: Address already in use: JVM_Bind
[16:08:48 WARN]:        at java.net.DualStackPlainSocketImpl.bind0(Native Method)
[16:08:48 WARN]:        at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
[16:08:48 WARN]:        at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
[16:08:48 WARN]:        at java.net.PlainSocketImpl.bind(Unknown Source)
[16:08:48 WARN]:        at java.net.ServerSocket.bind(Unknown Source)
[16:08:48 WARN]:        at java.net.ServerSocket.<init>(Unknown Source)
[16:08:48 WARN]:        at java.net.ServerSocket.<init>(Unknown Source)
[16:08:48 WARN]:        at com.macuyiko.minecraftpyserver.jython.TelnetServer.run(TelnetServer.java:29)
[16:08:48 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:08:48 WARN]: Exception in thread "Thread-27"
[16:08:48 WARN]: java.lang.NullPointerException
[16:08:48 WARN]:        at com.macuyiko.minecraftpyserver.jython.TelnetServer.run(TelnetServer.java:40)
[16:08:48 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:08:48 WARN]: [WebSocketSelector-109] ERROR org.java_websocket.server.WebSocketServer - Shutdown due to fatal error
[16:08:48 WARN]: java.net.BindException: Address already in use: bind
[16:08:48 WARN]:        at sun.nio.ch.Net.bind0(Native Method)
[16:08:48 WARN]:        at sun.nio.ch.Net.bind(Unknown Source)
[16:08:48 WARN]:        at sun.nio.ch.Net.bind(Unknown Source)
[16:08:48 WARN]:        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
[16:08:48 WARN]:        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
[16:08:48 WARN]:        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
[16:08:48 WARN]:        at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:505)
[16:08:48 WARN]:        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:315)
[16:08:48 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:08:48 WARN]: [MinecraftPyServer] onError on websocket
[16:08:48 WARN]: java.net.BindException: Address already in use: bind
[16:08:48 WARN]:        at sun.nio.ch.Net.bind0(Native Method)
[16:08:48 WARN]:        at sun.nio.ch.Net.bind(Unknown Source)
[16:08:48 WARN]:        at sun.nio.ch.Net.bind(Unknown Source)
[16:08:48 WARN]:        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
[16:08:48 WARN]:        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
[16:08:48 WARN]:        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
[16:08:48 WARN]:        at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:505)
[16:08:48 WARN]:        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:315)
[16:08:48 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by Macuyiko** [comment]
java.net.BindException: Address already in use: bind

You might have two copies running, or the default port for the websocket server (44445) is already being used by something else. You can change this in `config.yml`.
