### ISSUE TITLE
Getting strange error on all commands in minecraft

### ISSUE THREAD

**Issue by Tiebe** [Macuyiko/minecraft-python#28]
This is the error in console 
`> [12:26:15 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pyrestart' in plugin MinecraftPyServer v0.8
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[server.jar:git-Spigot-1a3504a-e7700ab]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-1a3504a-e7700ab]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[server.jar:git-Spigot-1a3504a-e7700ab]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1621) ~[server.jar:git-Spigot-1a3504a-e7700ab]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461) ~[server.jar:git-Spigot-1a3504a-e7700ab]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[server.jar:git-Spigot-1a3504a-e7700ab]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-1a3504a-e7700ab]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[server.jar:git-Spigot-1a3504a-e7700ab]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-1a3504a-e7700ab]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [server.jar:git-Spigot-1a3504a-e7700ab]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-1a3504a-e7700ab]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-1a3504a-e7700ab]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-1a3504a-e7700ab]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
at com.macuyiko.minecraftpyserver.MinecraftPyServerPlugin.send(MinecraftPyServerPlugin.java:53) ~[?:?]
at com.macuyiko.minecraftpyserver.jython.JyCommandExecutor.onCommand(JyCommandExecutor.java:43) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-1a3504a-e7700ab]
... 15 more
`
Would anyone be able to help? Thanks!

**Comment by Macuyiko** [comment]
Probably related to issue #27

Does the latest release fix this for you?

**Comment by spookybear0** [comment]
This seems solved and is inactive. I think it is safe to close this.
