### ISSUE TITLE
Error with EventExecutor in .eventRegister()

### ISSUE THREAD

**Issue by dmytrohoi** [Macuyiko/minecraft-python#30]
Server: Papper 1.15.2 (Spigot 1.15.2)

<details>
<summary>Plugin code</summary>

``` python
# /local/bin/python
# -*- coding: utf-8 -*-

from mcapi import *
from random import randint
from org.bukkit.event.player import PlayerRespawnEvent


X_MAX_LIMIT = 50
Z_MAX_LIMIT = 50

@asynchronous()
def respawn_randomly(event):
    player = event.getPlayer()
    player.chat('Respawn starts')
    if event.isBadRespawn():
        player.chat('Respawning in bed')
        return True

    player.chat('Respawning randomly on spawn location')
    respawn_location = event.getRespawnLocation()
    player.chat(str(respawn_location))
    x_position = randint(10, X_MAX_LIMIT)
    z_position = randint(10, Z_MAX_LIMIT)
    random_respawn_location = respawn_location.add(x=x_position, z=z_position)

    block_y = random_respawn_location.getBlockY()
    random_respawn_location.setY(block_y + 1)
    event.setRespawnLocation(random_respawn_location)

listener = add_event_listener(PlayerRespawnEvent, respawn_randomly)

```
</details>

<details>
<summary>Error log</summary>

``` log

[22:57:47 INFO]: [MinecraftPyServer] Enabling MinecraftPyServer v0.1*
[22:57:47 INFO]: [MinecraftPyServer] Loading MinecraftPyServerPlugin
[22:57:47 WARN]: [MinecraftPyServer] Unpacking: lib-common/
[22:57:47 WARN]: [MinecraftPyServer] Unpacking: lib-common/java-websocket-1.4.0.jar
[22:57:47 WARN]: [MinecraftPyServer] Unpacking: lib-common/jython-standalone-2.7.2.jar
[22:57:47 WARN]: [MinecraftPyServer] Unpacking: python/
[22:57:47 WARN]: [MinecraftPyServer] Unpacking: python/mcapi.py
[22:57:47 WARN]: [MinecraftPyServer] Adding: file:/home/dmytro.hoi/Documents/personal/test-server/lib-common/jython-standalone-2.7.2.jar
[22:57:47 WARN]: [MinecraftPyServer] Adding: file:/home/dmytro.hoi/Documents/personal/test-server/lib-common/java-websocket-1.4.0.jar
[22:57:47 WARN]: [MinecraftPyServer] Parsing plugin: random-respawn-plugin.py
[22:57:51 INFO]: MCAPI activating
[22:57:52 ERROR]: Error occurred while enabling MinecraftPyServer v0.1 (Is it up to date?)
org.python.core.PyException: TypeError: registerEvent(): 4th arg can't be coerced to org.bukkit.plugin.EventExecutor
at org.python.core.Py.TypeError(Py.java:236) ~[?:?]
at org.python.core.PyReflectedFunction.throwError(PyReflectedFunction.java:213) ~[?:?]
at org.python.core.PyReflectedFunction.throwBadArgError(PyReflectedFunction.java:316) ~[?:?]
at org.python.core.PyReflectedFunction.throwError(PyReflectedFunction.java:325) ~[?:?]
at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:171) ~[?:?]
at org.python.core.PyObject.__call__(PyObject.java:422) ~[?:?]
at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237) ~[?:?]
at org.python.core.PyMethod.__call__(PyMethod.java:228) ~[?:?]
at org.python.core.PyMethod.__call__(PyMethod.java:218) ~[?:?]
at mcapi$py.add_event_listener$31(/home/dmytro.hoi/Documents/personal/test-server/python/mcapi.py:130) ~[?:?]
at mcapi$py.call_function(/home/dmytro.hoi/Documents/personal/test-server/python/mcapi.py) ~[?:?]
at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[?:?]
at org.python.core.PyBaseCode.call(PyBaseCode.java:306) ~[?:?]
at org.python.core.PyBaseCode.call(PyBaseCode.java:141) ~[?:?]
at org.python.core.PyFunction.__call__(PyFunction.java:426) ~[?:?]
at org.python.pycode._pyx0.f$0(/home/dmytro.hoi/Documents/personal/test-server/./python-plugins/random-respawn-plugin.py:36) ~[?:?]
at org.python.pycode._pyx0.call_function(/home/dmytro.hoi/Documents/personal/test-server/./python-plugins/random-respawn-plugin.py) ~[?:?]
at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[?:?]
at org.python.core.PyCode.call(PyCode.java:18) ~[?:?]
at org.python.core.Py.runCode(Py.java:1687) ~[?:?]
at org.python.core.__builtin__.execfile_flags(__builtin__.java:535) ~[?:?]
at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:287) ~[?:?]
at com.macuyiko.minecraftpyserver.jython.JyInterpreter.execfile(JyInterpreter.java:127) ~[?:?]
at com.macuyiko.minecraftpyserver.MinecraftPyServerPlugin.onEnable(MinecraftPyServerPlugin.java:53) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-239]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-239]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-239]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:471) ~[patched_1.15.2.jar:git-Paper-239]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:385) ~[patched_1.15.2.jar:git-Paper-239]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-239]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-239]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895) ~[patched_1.15.2.jar:git-Paper-239]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[22:57:52 INFO]: [MinecraftPyServer] Disabling MinecraftPyServer v0.1
[22:57:52 INFO]: [MinecraftPyServer] Unloading MinecraftPyServerPlugin

```

</details>

With code in example, same result:

<details>
<summary>Code error logs from the example README.md</summary>

``` log

[23:02:50 WARN]: [MinecraftPyServer] Unpacking: lib-common/
[23:02:50 WARN]: [MinecraftPyServer] Unpacking: lib-common/java-websocket-1.4.0.jar
[23:02:50 WARN]: [MinecraftPyServer] Unpacking: lib-common/jython-standalone-2.7.2.jar
[23:02:50 WARN]: [MinecraftPyServer] Unpacking: python/
[23:02:50 WARN]: [MinecraftPyServer] Unpacking: python/mcapi.py
[23:02:50 WARN]: [MinecraftPyServer] Adding: file:/home/dmytro.hoi/Documents/personal/test-server/lib-common/jython-standalone-2.7.2.jar
[23:02:50 WARN]: [MinecraftPyServer] Adding: file:/home/dmytro.hoi/Documents/personal/test-server/lib-common/java-websocket-1.4.0.jar
[23:02:50 WARN]: [MinecraftPyServer] Parsing plugin: random-respawn-plugin.py
[23:02:54 INFO]: MCAPI activating
[23:02:55 ERROR]: Error occurred while enabling MinecraftPyServer v0.1 (Is it up to date?)
org.python.core.PyException: TypeError: registerEvent(): 4th arg can't be coerced to org.bukkit.plugin.EventExecutor
at org.python.core.Py.TypeError(Py.java:236) ~[?:?]
at org.python.core.PyReflectedFunction.throwError(PyReflectedFunction.java:213) ~[?:?]
at org.python.core.PyReflectedFunction.throwBadArgError(PyReflectedFunction.java:316) ~[?:?]
at org.python.core.PyReflectedFunction.throwError(PyReflectedFunction.java:325) ~[?:?]
at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:171) ~[?:?]
at org.python.core.PyObject.__call__(PyObject.java:422) ~[?:?]
at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237) ~[?:?]
at org.python.core.PyMethod.__call__(PyMethod.java:228) ~[?:?]
at org.python.core.PyMethod.__call__(PyMethod.java:218) ~[?:?]
at mcapi$py.add_event_listener$31(/home/dmytro.hoi/Documents/personal/test-server/python/mcapi.py:130) ~[?:?]
at mcapi$py.call_function(/home/dmytro.hoi/Documents/personal/test-server/python/mcapi.py) ~[?:?]
at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[?:?]
at org.python.core.PyBaseCode.call(PyBaseCode.java:306) ~[?:?]
at org.python.core.PyBaseCode.call(PyBaseCode.java:141) ~[?:?]
at org.python.core.PyFunction.__call__(PyFunction.java:426) ~[?:?]
at org.python.pycode._pyx0.f$0(/home/dmytro.hoi/Documents/personal/test-server/./python-plugins/random-respawn-plugin.py:19) ~[?:?]
at org.python.pycode._pyx0.call_function(/home/dmytro.hoi/Documents/personal/test-server/./python-plugins/random-respawn-plugin.py) ~[?:?]
at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[?:?]
at org.python.core.PyCode.call(PyCode.java:18) ~[?:?]
at org.python.core.Py.runCode(Py.java:1687) ~[?:?]
at org.python.core.__builtin__.execfile_flags(__builtin__.java:535) ~[?:?]
at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:287) ~[?:?]
at com.macuyiko.minecraftpyserver.jython.JyInterpreter.execfile(JyInterpreter.java:127) ~[?:?]
at com.macuyiko.minecraftpyserver.MinecraftPyServerPlugin.onEnable(MinecraftPyServerPlugin.java:53) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-239]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-239]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-239]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:471) ~[patched_1.15.2.jar:git-Paper-239]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:385) ~[patched_1.15.2.jar:git-Paper-239]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-239]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-239]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895) ~[patched_1.15.2.jar:git-Paper-239]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[23:02:55 INFO]: [MinecraftPyServer] Disabling MinecraftPyServer v0.1
[23:02:55 INFO]: [MinecraftPyServer] Unloading MinecraftPyServerPlugin

```

</details>

Fix PR #31

**Comment by dmytrohoi** [comment]
I found a way to fix this.

All changes are checked and applied to PR #31 .
