### ISSUE TITLE
Error: java.net.BindException: Address already in use: bind

### ISSUE THREAD

**Issue by QboiDev** [Macuyiko/minecraft-python#33]
Failed to bind adress:

```
[18:10:16 WARN]: java.net.BindException: Address already in use: JVM_Bind
[18:10:16 WARN]:        at java.net.DualStackPlainSocketImpl.bind0(Native Method)
[18:10:16 WARN]:        at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
[18:10:16 WARN]:        at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
[18:10:16 WARN]:        at java.net.PlainSocketImpl.bind(Unknown Source)
[18:10:16 WARN]:        at java.net.ServerSocket.bind(Unknown Source)
[18:10:16 WARN]:        at java.net.ServerSocket.<init>(Unknown Source)
[18:10:16 WARN]:        at java.net.ServerSocket.<init>(Unknown Source)
[18:10:16 WARN]:        at com.macuyiko.minecraftpyserver.jython.TelnetServer.run(TelnetServer.java:29)
[18:10:16 WARN]:        at java.lang.Thread.run(Unknown Source)
[18:10:16 WARN]: Exception in thread "Thread-141" java.lang.NullPointerException
[18:10:16 WARN]:        at com.macuyiko.minecraftpyserver.jython.TelnetServer.run(TelnetServer.java:40)
[18:10:16 WARN]:        at java.lang.Thread.run(Unknown Source)
[18:10:16 ERROR]: [org.java_websocket.server.WebSocketServer] Shutdown due to fatal error
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_251]
        at sun.nio.ch.Net.bind(Unknown Source) ~[?:1.8.0_251]
        at sun.nio.ch.Net.bind(Unknown Source) ~[?:1.8.0_251]
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source) ~[?:1.8.0_251]
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source) ~[?:1.8.0_251]
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source) ~[?:1.8.0_251]
        at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:505) ~[?:?]
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:315) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
```

What port(s) is the telnet server on? I saw it is not on port 23 (wich is default for telnet).

**Comment by Macuyiko** [comment]
These are the defaults:

pythonconsole:
 telnetport: 44444
 websocketport: 44445
 enablechatcommands: true
 disconnecttimeout: 900
