### ISSUE TITLE
Error when trying to launch server with Plugin installed.

### ISSUE THREAD

**Issue by AbnormalMatrix** [Macuyiko/minecraft-python#34]
Hi,
This seems like a really cool project and I would love to make some plugins that are written in Python. I started by downloading the latest release and putting the jar file in the plugins directory. When I start the server it starts normally and it created the folders "python" and "lib-common". However, when the server starts I get this in the console. `[16:56:21 INFO]: [MinecraftPyServer] Enabling MinecraftPyServer v0.1
[16:56:21 INFO]: [MinecraftPyServer] Loading MinecraftPyServerPlugin
[16:56:21 WARN]: java.io.FileNotFoundException: /Users/user/Desktop/test%20server/plugins/python.jar (No such file or directory)
[16:56:21 WARN]: 	at java.util.zip.ZipFile.open(Native Method)
[16:56:21 WARN]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[16:56:21 WARN]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[16:56:21 WARN]: 	at java.util.jar.JarFile.<init>(JarFile.java:167)
[16:56:21 WARN]: 	at java.util.jar.JarFile.<init>(JarFile.java:104)
[16:56:21 WARN]: 	at com.macuyiko.minecraftpyserver.MinecraftPyServerUtils.unpack(MinecraftPyServerUtils.java:35)
[16:56:21 WARN]: 	at com.macuyiko.minecraftpyserver.MinecraftPyServerUtils.setup(MinecraftPyServerUtils.java:20)
[16:56:21 WARN]: 	at com.macuyiko.minecraftpyserver.MinecraftPyServerPlugin.onEnable(MinecraftPyServerPlugin.java:27)
[16:56:21 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:56:21 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[16:56:21 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[16:56:21 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
[16:56:21 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
[16:56:21 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
[16:56:21 WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267)
[16:56:21 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
[16:56:21 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:56:21 WARN]: java.io.FileNotFoundException: /Users/user/Desktop/test%20server/plugins/python.jar (No such file or directory)
[16:56:21 WARN]: 	at java.util.zip.ZipFile.open(Native Method)
[16:56:21 WARN]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[16:56:21 WARN]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[16:56:21 WARN]: 	at java.util.jar.JarFile.<init>(JarFile.java:167)
[16:56:21 WARN]: 	at java.util.jar.JarFile.<init>(JarFile.java:104)
[16:56:21 WARN]: 	at com.macuyiko.minecraftpyserver.MinecraftPyServerUtils.unpack(MinecraftPyServerUtils.java:35)
[16:56:21 WARN]: 	at com.macuyiko.minecraftpyserver.MinecraftPyServerUtils.setup(MinecraftPyServerUtils.java:21)
[16:56:21 WARN]: 	at com.macuyiko.minecraftpyserver.MinecraftPyServerPlugin.onEnable(MinecraftPyServerPlugin.java:27)
[16:56:21 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:56:21 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[16:56:21 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[16:56:21 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
[16:56:21 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
[16:56:21 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
[16:56:21 WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267)
[16:56:21 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
[16:56:21 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:56:21 ERROR]: Error occurred while enabling MinecraftPyServer v0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/java_websocket/server/WebSocketServer
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_251]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_251]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:142) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:202) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:103) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_251]
	at com.macuyiko.minecraftpyserver.MinecraftPyServerPlugin.startWebSocketServer(MinecraftPyServerPlugin.java:89) ~[?:?]
	at com.macuyiko.minecraftpyserver.MinecraftPyServerPlugin.onEnable(MinecraftPyServerPlugin.java:37) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.ClassNotFoundException: org.java_websocket.server.WebSocketServer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:146) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_251]
	... 20 more`
Which is a problem. I then try to save a .py file just in the main directory of the server with this: 
`from mcapi import *
from time import sleep
from random import randint

from org.bukkit.event.player import PlayerJoinEvent

@asynchronous()
def join_event(e):
    player = e.getPlayer()
    player_location = location(player)
    player_location.y += 20
    yell("A chickeny hello to player %s" % (player.getName(),))
    for i in range(10):
        spawn(player_location)

listener = add_event_listener(PlayerJoinEvent, join_event)
` 
Then I do /pyload test.py and I just get a message saying "/pyload file"
I also tried putting the .py file in a folder called "python-plugins" but I got the same result.
Any suggestions?
Thanks!

**Comment by Macuyiko** [comment]
Probably related to #29 -- does the latest release fix this for you?

**Comment by AbnormalMatrix** [comment]
Yes, the latest release has fixed the issue. Thanks!
