### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by 5mmx** [Macuyiko/minecraft-python#46]
Getting an error while running this on a fresh new server running paper 1.16.5 with only this plugin and nothing else. Here is the error:
`[18:30:16] [Server thread/ERROR]: Error occurred while enabling MinecraftPyServer v0.12 (Is it up to date?)
java.lang.NoClassDefFoundError: org/java_websocket/server/WebSocketServer
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201) ~[minecraft_server.jar:git-Paper-776]
at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[minecraft_server.jar:git-Paper-776]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[minecraft_server.jar:git-Paper-776]
at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
at com.macuyiko.minecraftpyserver.MinecraftPyServerPlugin.startWebSocketServer(MinecraftPyServerPlugin.java:144) ~[?:?]
at com.macuyiko.minecraftpyserver.MinecraftPyServerPlugin.onEnable(MinecraftPyServerPlugin.java:48) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[minecraft_server.jar:git-Paper-776]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[minecraft_server.jar:git-Paper-776]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[minecraft_server.jar:git-Paper-776]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[minecraft_server.jar:git-Paper-776]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[minecraft_server.jar:git-Paper-776]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[minecraft_server.jar:git-Paper-776]
[18:32]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[minecraft_server.jar:git-Paper-776]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[minecraft_server.jar:git-Paper-776]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[minecraft_server.jar:git-Paper-776]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: org.java_websocket.server.WebSocketServer
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[minecraft_server.jar:git-Paper-776]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[minecraft_server.jar:git-Paper-776]
at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
... 20 more`

**Comment by Macuyiko** [comment]
This is most likely due to newer Java version. To verify.

**Comment by 5mmx** [comment]
Probable, will try to verify with other java versions and let you know

**Comment by Macuyiko** [comment]
I've found a workaround which should work on Java 16, thanks to Spigot having dealt with a related problem already (i.e. library loading).  Should be fixed by commit da6c5c17a4dc96ce2798996baa109c29f89781f7 and included in an upcoming release.

**Comment by Macuyiko** [comment]
The new release should fix this.

**Comment by 5mmx** [comment]
👍
