### ISSUE TITLE
How to give player potion Effect?

### ISSUE THREAD

**Issue by VincentX0905** [Macuyiko/minecraft-python#66]
i try use:
`player.addPotionEffect(org.bukkit.potion.PotionEffect(org.bukkit.potion.PotionEffectType.INCREASE_DAMAGE, 999999, 1))`
and
`player.addPotionEffect(PotionEffect(PotionEffectType.INCREASE_DAMAGE, 999999, 1))`
but it not working...

**Comment by VincentX0905** [comment]
This is error
```java
[22:11:25 WARN]: Exception in thread Thread-1:Traceback (most recent call last):
[22:11:25 WARN]:   File "C:\Users\vince\Desktop\MC\lib-common\jython-standalone-2.7.2.jar\Lib\threading.py", line 222, in _Thread__bootstrap
[22:11:25 WARN]:     self.run()
[22:11:25 WARN]:   File "C:\Users\vince\Desktop\MC\lib-common\jython-standalone-2.7.2.jar\Lib\threading.py", line 213, in run
[22:11:25 WARN]:     self._target(*self._args, **self._kwargs)
[22:11:25 WARN]:   File "C:\Users\vince\Desktop\MC\python\mcapi.py", line 108, in <lambda>
[22:11:25 WARN]:     Thread(target=lambda: wrap_exception(execfunc)).start()
[22:11:25 WARN]:   File "C:\Users\vince\Desktop\MC\python\mcapi.py", line 104, in wrap_exception
[22:11:25 WARN]:     g()
[22:11:25 WARN]:   File "C:\Users\vince\Desktop\MC\python\mcapi.py", line 104, in wrap_exception
[22:11:25 WARN]:     g()
[22:11:25 WARN]:   File "C:\Users\vince\Desktop\MC\python\mcapi.py", line 125, in <lambda>
[22:11:25 WARN]:     g = lambda: f(*args, **kwargs)
[22:11:25 WARN]:   File "C:\Users\vince\Desktop\MC\.\python-plugins\skill.py", line 57, in join_event
[22:11:25 WARN]:     frist_effect(uuid,player)
[22:11:25 WARN]:   File "C:\Users\vince\Desktop\MC\.\python-plugins\skill.py", line 43, in frist_effect
[22:11:25 WARN]:     player.addPotionEffect(PotionEffect(PotionEffectType.INCREASE_DAMAGE, 999999, 1))
[22:11:25 WARN]: IllegalStateException: java.lang.IllegalStateException: Asynchronous effect add!
```

**Comment by Macuyiko** [comment]
As the exception indicates, this should be executed synchronously, e.g. as follows:

```python
from mcapi import *
from org.bukkit.potion import PotionEffect, PotionEffectType

@synchronous()
def add_potion(p):
    print("Adding potion effect to:", p)
    p.addPotionEffect(
        PotionEffect(PotionEffectType.INCREASE_DAMAGE, 999999, 1)
    )

add_potion(player())
```

**Comment by VincentX0905** [comment]
Thank you! it working!
bc i am python dev not java dev
So I don't know much about JAVA
